namePrefix: dvn-
nameSuffix: -prod
resources:
  - backend/deploy.yml
  - backend/service.yml
  - frontend/deploy.yml
  - frontend/service.yml

images:
  - name: 917714909985.dkr.ecr.us-east-1.amazonaws.com/workshop/production/backend
    newName: 917714909985.dkr.ecr.us-east-1.amazonaws.com/workshop/production/backend
    newTag: v1.0

  - name: 917714909985.dkr.ecr.us-east-1.amazonaws.com/workshop/production/frontend
    newName: 917714909985.dkr.ecr.us-east-1.amazonaws.com/workshop/production/frontend
    newTag: v1.0